name    'severalnines-clustercontrol'
version '0.0.1'
source ''
author 'Ashraf Sharif'
license ''
summary ''
description ''
project_page ''

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
