name    'severalnines-clustercontrol'
version '0.1.3'
source 'https://github.com/severalnines/puppet'
author 'Ashraf Sharif'
license 'Copyright (C) 2014 Severalnines AB. Licensed under the Licensed under (Apache 2.0).'
summary 'Installs ClusterControl on your existing database cluster.'
description 'ClusterControl is a management and automation software for database clusters. It helps deploy, monitor, manager and scale your database cluster. This module will install ClusterControl and configure it to manage and monitor an existing database cluster. 

Supported database clusters:
* Galera Cluster for MySQL
* Percona XtraDB Cluster
* MariaDB Galera Cluster
* MySQL Replication
* MySQL Cluster
* MongoDB Replica Set
* MongoDB Sharded Cluster
* TokuMX Cluster'
project_page '(https://forge.puppetlabs.com/severalnines/clustercontrol)'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
